[functions.create-draft]
enabled = true
verify_jwt = true
import_map = "./functions/create-draft/deno.json"
entrypoint = "./functions/create-draft/index.ts"

[functions.process-queue]
verify_jwt = false

[functions.find-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false
